bugifx undefined method `bitemporal_include?'
bugfix `undefined method`.
```ruby
# error: `block in _except_valid_from': undefined method `bitemporal_include?' for "created_at IS NULL":String (NoMethodError)
puts Employee.where("created_at IS NULL").valid_at("2020/04/01").except_bitemporal_datetime.to_sql
```